apiVersion: v1
kind: Pod
metadata:
  name: {{ .Values.component }}
  labels:
    component: {{ .Values.component }}
spec:
  containers:
    - name: {{ .Values.component }}
      image: 569313928762.dkr.ecr.us-east-1.amazonaws.com/{{ .Values.component }}:{{ .Values.appversion }}
      volumeMounts:
        - mountPath: /params
          name: params
  initContainers:
    - name: aws-ssm-param-store-initcont
      image: 569313928762.dkr.ecr.us-east-1.amazonaws.com/aws-ssm-param-store-initcont:1.0.2
      args: [ "{{ .Values.params }}" ]
      volumeMounts:
        - mountPath: /params
          name: params
  serviceAccountName: {{ .Values.component }}
  volumes:
  - name: params
    emptyDir:
      sizeLimit: 100Mi